### PR TITLE
feat: support annotations for gauge specs

### PR DESCRIPTION
**Pull request by v0lkc**
Adds support for [gauge specs](https://docs.gauge.org/writing-specifications.html?os=macos&language=javascript&ide=vscode) annotations. 

## Notation

Requirements can be annotated either on a `spec` or on a `scenario` level using the following notation:

```markdown
Trace: <RequirementSystem>:<RequirementId>, <RequirementSystem>:<RequirementId>, ...
```

## Sample

```markdown
# gauge spec
Trace: Jira:MYPROJECT-123

## gauge scenario
Trace: Jira:MYPROJECT-321, Jira:MYPROJECT:432

* step 1
* step 2
```

### CODE REVIEW

**Comment by doergn** [comment]
@v0lkc Nice, thanks! Could you also add the guage option in the wiki documentation?

**Comment by v0lkc** [comment]
@doergn Currently working on it. :-) Do you mind if I update the go dependencies along with this PR? Otherwise I would open a 2nd one.

**Comment by doergn** [comment]
`Do you mind if I update the go dependencies along with this PR?`
No, sure. Go ahead.

**Comment by doergn** [comment]
Checked locally. All test pass.

**Pull request merged**
